import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png" />
      </Head>

      <main className="">
        <a
          href="https://wa.me/62895700721023"
          className="group drop-shadow-lg z-50 fixed right-0 bottom-32 my-8 justify-center items-center order-2 hidden md:block"
        >
          <div className="flex py-2 px-3 bg-green-800 group-hover:bg-green-700 rounded-l-full gap-2 items-center ">
            <Image
              src="/img/wa.png"
              alt="wa"
              width="35"
              height="35"
              className="drop-shadow-lg group-hover:-rotate-12 group-hover:translate-x-2 duration-300"
            />
          </div>
        </a>

        <a
          href="https://wa.me/62895707823311"
          className="group drop-shadow-lg z-50 fixed right-0 bottom-16 my-8 justify-center items-center order-2 hidden md:block"
        >
          <div className="flex py-2 px-3 bg-green-800 group-hover:bg-green-700 rounded-l-full gap-2 items-center ">
            <Image
              src="/img/wa.png"
              alt="wa"
              width="35"
              height="35"
              className="drop-shadow-lg group-hover:-rotate-12 group-hover:translate-x-2 duration-300"
            />
          </div>
        </a>

        <a
          href="https://www.tokopedia.com/optimaglass"
          className="group drop-shadow-lg z-50 fixed right-0 bottom-0 my-8 justify-center items-center order-2 hidden md:block"
        >
          <div className="flex py-1 px-3 bg-green-800 group-hover:bg-green-700 rounded-l-full gap-2 items-center ">
            <Image
              src="/img/tokopedia.png"
              alt="wa"
              width="35"
              height="35"
              className="drop-shadow-lg group-hover:-rotate-12 group-hover:translate-x-2 duration-300"
            />
          </div>
        </a>
      </main>

      <footer className=""></footer>
    </div>
  );
}
